version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: bovmonitor-db-local
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bovmonitor
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local